# Generated by Django 4.0.3 on 2022-05-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blogs_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='small_dec',
            new_name='small_desc',
        ),
    ]
